name = "MyRegistry"
uuid = "5166b0fb-80be-445f-af2b-7ca0bfe85ad7"
repo = "https://github.com/gpena/MyRegistry.git"
description = "My private registry"

[packages]
72287966-2ff3-4442-8755-61ed245be5f7 = { name = "Bramble", path = "B/Bramble" }
